apache/apisix:
    - apache/apisix
    - apache/apisix-dashboard
    - apache/apisix-ingress-controller
    - apache/apisix-docker
    - apache/apisix-helm-chart
    - apache/apisix-control-plane
    - apache/apisix-website
    - apache/apisix-dashboard-built
    - apache/apisix-ingress-docker
    - api7/lua-resty-etcd
    - api7/lua-resty-radixtree
    - api7/lua-resty-ipmatcher
    - api7/lua-var-nginx-module
    - api7/envoy-apisix
    - api7/apisix-build-tools
apache/skywalking:
    - apache/skywalking
    - apache/skywalking-rocketbot-ui
    - apache/skywalking-website
    - apache/skywalking-nginx-lua
    - apache/skywalking-kong
    - apache/skywalking-python
    - apache/skywalking-nodejs
    - apache/skywalking-client-js
    - apache/skywalking-satellite
    - apache/skywalking-cli
    - apache/skywalking-kubernetes
    - apache/skywalking-swck
    - apache/skywalking-docker
    - apache/skywalking-data-collect-protocol
    - apache/skywalking-query-protocol
    - apache/skywalking-goapi
    - apache/skywalking-agent-test-tool
    - apache/skywalking-eyes
    - SkyAPM/SkyAPM-dotnet
    - SkyAPM/go2sky
    - SkyAPM/go2sky-plugins
    - SkyAPM/SkyAPM-php-sdk
    - SkyAPM/SkyAPM-nodejs
    - SkyAPM/cpp2sky
    - sourceplusplus/SourceMarker
    - SkyAPM/java-plugin-extensions
    - SkyAPM/uranus
apache/openwhisk:
    - apache/openwhisk
    - apache/openwhisk-apigateway
    - apache/openwhisk-catalog
    - apache/openwhisk-cli
    - apache/openwhisk-client-go
    - apache/openwhisk-client-js
    - apache/openwhisk-composer
    - apache/openwhisk-composer-python
    - apache/openwhisk-deploy-kube
    - apache/openwhisk-deploy-mesos
    - apache/openwhisk-devtools
    - apache/openwhisk-external-resources
    - apache/openwhisk-intellij-plugin
    - apache/openwhisk-package-alarms
    - apache/openwhisk-package-cloudant
    - apache/openwhisk-package-deploy
    - apache/openwhisk-package-kafka
    - apache/openwhisk-package-pushnotifications
    - apache/openwhisk-pluggable-provider
    - apache/openwhisk-release
    - apache/openwhisk-runtime-ballerina
    - apache/openwhisk-runtime-deno
    - apache/openwhisk-runtime-docker
    - apache/openwhisk-runtime-dotnet
    - apache/openwhisk-runtime-go
    - apache/openwhisk-runtime-java
    - apache/openwhisk-runtime-nodejs
    - apache/openwhisk-runtime-php
    - apache/openwhisk-runtime-python
    - apache/openwhisk-runtime-ruby
    - apache/openwhisk-runtime-rust
    - apache/openwhisk-runtime-swift
    - apache/openwhisk-slackinvite
    - apache/openwhisk-test
    - apache/openwhisk-utilities
    - apache/openwhisk-vscode-extension
    - apache/openwhisk-website
    - apache/openwhisk-wskdebug
    - apache/openwhisk-wskdeploy
