name: Deploy website

on:
  push:
    branches:
      - deploy-S3

jobs:
  deploy-website:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 14.x

      - name: Install website dependencies
        run: yarn install

      - name: Build website
        run: yarn build
        
      - name: Upload files to AWS S3
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
            accessKeyId: ${{ secrets }}
            accessKeySecret: ${{ secrets }}
            bucket: "contributor-graph"
            endpoint: "http://oss-accelerate.aliyuncs.com/" 
            folder: "build"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Deploy
        run: aws s3 sync ./build s3://git-contributor
