name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  deploy-website:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 14.x

      - name: Install website dependencies
        run: yarn install

      - name: Build website
        run: yarn build

      - name: Upload files to COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
            args: delete -r -f / && upload -r ./build/ /
            secret_id: ${{ secrets.TENCENT_COS_SECRET_ID }}
            secret_key: ${{ secrets.TENCENT_COS_SECRET_KEY }}
            bucket: ${{ secrets.TENCENT_COS_BUCKET }}
            region: ap-guangzhou
