name: Deploy website

on:
  push:
    branches:
      - feat-add-deploy-website-COS

jobs:
  deploy-website:
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 14.x

      - name: Install website dependencies
        run: yarn install

      - name: Build website
        run: yarn build
        
      # - name: Upload files to OSS
      #   uses: fangbinwei/aliyun-oss-website-action@v1
      #   with:
      #       accessKeyId: ${{ secrets.ALIYUN_OSS_ACCESSKEY }}
      #       accessKeySecret: ${{ secrets.ALIYUN_OSS_ACCESSKEYSECRET }}
      #       bucket: "contributor-graph"
      #       endpoint: "http://oss-accelerate.aliyuncs.com/" 
      #       folder: "build"

      - name: Upload files to COS
        uses: zkqiang/tencent-cos-action@v0.1.0
        with:
            args: upload -r ./build /
            secret_id: ${{ secrets.TENCENT_COS_SECRET_ID }}
            secret_key: ${{ secrets.TENCENT_COS_SECRET_KEY }}
            bucket: ${{ secrets.TENCENT_COS_BUCKET }}
            region: ap-nanjing
